[build]
  publish = "dist"
  command = "npm install && npm run build"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

[[headers]]
  for = "/*" # Bảo vệ toàn bộ trang
  [headers.values]
    Authorization = "Basic dHVuZ2x5OmFzZEAxMjM="
